opsman_configuration:
  gcp:
    gcp_service_account: ((opsman_service_account_json))
    project: sa-aelmore
    region: us-west1
    zone: us-west1-b
    vm_name: gcplab01-ops-manager-vm               # default: OpsManager-vm
    # For SharedVPC: projects/[HOST_PROJECT_ID]/regions/[REGION]/subnetworks/[SUBNET]
    vpc_subnet: gcplab01-infrastructure-subnet
    tags: gcplab01-ops-manager-external   # must match what terraform uses for firewall purposes???
    custom_cpu: 2                         # default:  8
    custom_memory: 8                      # default: 16
    boot_disk_size: 150                   # default: 400
    # At least one IP address (public or private) needs to be assigned to the VM.
    public_ip: 104.196.248.181
    private_ip: 10.0.0.2

opsman_env:
  target: https://pcf.lab01.differentscale.com
  connect-timeout: 30            # default 5
  request-timeout: 1800          # default 1800
  skip-ssl-validation: true     # default false
  username: ((opsman_admin_username))
  password: ((opsman_admin_password))
  decryption-passphrase: ((decryption_passphrase))