metrics_polling_interval: 30
on-demand-broker/canaries: 1
on-demand-broker/global_service_instance_quota: 20
on-demand-broker/max_in_flight: 3
on_demand_broker_plan_1_cf_service_access: enable
on_demand_broker_plan_1_description: This plan provides a single dedicated RabbitMQ
  3.7 node
on_demand_broker_plan_1_features: RabbitMQ 3.7
on_demand_broker_plan_1_instance_quota: 10
on_demand_broker_plan_1_name: single-node-3.7
on_demand_broker_plan_1_rabbitmq_cluster_partition_handling_strategy: pause_minority
on_demand_broker_plan_1_rabbitmq_number_of_nodes: 1
syslog_selector/enabled/syslog_tls: false
syslog_selector/enabled/syslog_transport: tcp
