cf-redis-broker/redis_maxmemory: 512MB
cf-redis-broker/service_instance_limit: 5
large_plan_selector/active/cf_service_access: enable
large_plan_selector/active/description: This plan provides a large dedicated Redis
  instance, tailored for caching use-cases with persistence to disk enabled
large_plan_selector/active/instance_limit: 20
large_plan_selector/active/lua_scripting: false
large_plan_selector/active/maxclients: 10000
large_plan_selector/active/name: cache-large
large_plan_selector/active/tcp_keepalive: 60
large_plan_selector/active/timeout: 3600
medium_plan_selector/active/cf_service_access: enable
medium_plan_selector/active/description: This plan provides a medium dedicated Redis
  instance, tailored for caching use-cases with persistence to disk enabled
medium_plan_selector/active/instance_limit: 20
medium_plan_selector/active/lua_scripting: false
medium_plan_selector/active/maxclients: 5000
medium_plan_selector/active/name: cache-medium
medium_plan_selector/active/tcp_keepalive: 60
medium_plan_selector/active/timeout: 3600
metrics_polling_interval: 30
redis-on-demand-broker/maximum_parallel_upgrades: 1
redis-on-demand-broker/service_instance_limit: 20
redis-on-demand-broker/service_instance_sharing: false
redis-on-demand-broker/upgrade_canary_number: 1
small_plan_selector/active/cf_service_access: enable
small_plan_selector/active/description: This plan provides a small dedicated Redis
  instance, tailored for caching use-cases with persistence to disk enabled
small_plan_selector/active/instance_limit: 20
small_plan_selector/active/lua_scripting: false
small_plan_selector/active/maxclients: 1000
small_plan_selector/active/name: cache-small
small_plan_selector/active/tcp_keepalive: 60
small_plan_selector/active/timeout: 3600
syslog_selector/active/syslog_transport: tcp
