add_app_info: false
app_cache_invalidate_ttl: 0s
app_limits: 0
consumer_queue_size: 10000
enable_event_tracing: false
flush_interval: 5s
hec_batch_size: 100
hec_retries: 5
hec_workers: 8
ignore_missing_app: true
missing_app_cache_invalidate_ttl: 0s
nozzle_memory: 256M
scale_out_nozzle: 2
skip_ssl_validation_cf: false
skip_ssl_validation_splunk: false
splunk_index: main
splunk_version: "6.6"
