autoscale_api_disable_connection_pooling: false
autoscale_api_instance_count: 1
autoscale_enable_verbose_logging: false
autoscale_instance_count: 3
autoscale_metric_bucket_count: 120
autoscale_scaling_interval_in_seconds: 35
ccdb_connection_validation_timeout: 3600
ccdb_read_timeout: 3600
cf_networking_database_connection_timeout: 120
cf_networking_enable_space_developer_self_service: false
cf_networking_internal_domain: apps.internal
cloud_controller/allow_app_ssh_access: true
cloud_controller/default_app_memory: 1024
cloud_controller/default_app_ssh_access: true
cloud_controller/default_disk_quota_app: 1024
cloud_controller/default_quota_max_number_services: 100
cloud_controller/default_quota_memory_limit_mb: 10240
cloud_controller/enable_custom_buildpacks: true
cloud_controller/max_disk_quota_app: 2048
cloud_controller/max_file_size: 1024
cloud_controller/security_event_logging_enabled: true
cloud_controller/staging_timeout_in_seconds: 900
cloud_controller_default_health_check_timeout: 60
cloud_controller_temporary_disable_deployments: false
container_networking_interface_plugin/silk/enable_log_traffic: false
container_networking_interface_plugin/silk/iptables_accepted_udp_logs_per_sec: 100
container_networking_interface_plugin/silk/iptables_denied_logs_per_sec: 1
container_networking_interface_plugin/silk/network_mtu: 1454
container_networking_interface_plugin/silk/vtep_port: 4789
credhub_key_encryption_passwords_0/primary: false
credhub_key_encryption_passwords_0/provider: internal
diego_brain/starting_container_count_maximum: 200
diego_database_max_open_connections: 100
doppler/message_drain_buffer_size: 10000
enable_cf_metric_name: false
enable_smb_volume_driver: false
enable_tls_to_internal_pxc: false
experimental_dynamic_egress_enforcement: false
garden_disk_cleanup/reserved/reserved_space_for_other_jobs_in_mb: 15360
gorouter_ssl_ciphers: ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
ha_proxy/skip_cert_verify: false
haproxy_max_buffer_size: 16384
haproxy_ssl_ciphers: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
locket_database_max_open_connections: 200
metric_registrar_blacklisted_tags: deployment,job,index,id
metric_registrar_enabled: false
metric_registrar_scrape_interval_in_seconds: 35
mysql/cli_history: true
mysql/max_connections: 3500
mysql/prevent_node_auto_rejoin: false
mysql/remote_admin_access: false
mysql_activity_logging/enable/audit_logging_events: connect,query
mysql_monitor/poll_frequency: 30
mysql_monitor/write_read_delay: 20
mysql_proxy/shutdown_delay: 30
mysql_proxy/startup_delay: 0
networkpolicyserver_database_max_open_connections: 200
networkpolicyserverinternal_database_max_open_connections: 200
nfs_server/blobstore_internal_access_rules: allow 10.0.0.0/8;,allow 172.16.0.0/12;,allow
  192.168.0.0/16;
push_apps_manager_app_poll_interval: 10
push_apps_manager_currency_lookup: '{ "usd": "$", "eur": "€" }'
push_apps_manager_display_plan_prices: false
push_apps_manager_enable_invitations: true
push_apps_manager_poll_interval: 30
route_services/enable/ignore_ssl_cert_verification: false
router/disable_insecure_cookies: false
router/drain_wait: 20
router/enable_isolated_routing: false
router/enable_write_access_logs: true
router/enable_zipkin: true
router/frontend_idle_timeout: 900
router/lb_healthy_threshold: 20
router/request_timeout_in_seconds: 900
router_backend_max_conn: 500
router_enable_proxy: false
routing_disable_http: false
saml_signature_algorithm: SHA256
secure_service_instance_credentials: false
silk_database_max_open_connections: 200
smtp_auth_mechanism: plain
smtp_enable_starttls_auto: false
syslog_drop_debug: true
syslog_metrics_to_syslog_enabled: true
syslog_use_tcp_for_file_forwarding_local_transport: false
system_blobstore_ccdroplet_max_staged_droplets_stored: 2
system_blobstore_ccpackage_max_valid_packages_stored: 2
uaa/apps_manager_access_token_lifetime: 3600
uaa/apps_manager_refresh_token_lifetime: 3600
uaa/cf_cli_access_token_lifetime: 7200
uaa/cf_cli_refresh_token_lifetime: 1209600
uaa/customize_password_label: Password
uaa/customize_username_label: Email
uaa/internal/password_expires_after_months: 0
uaa/internal/password_max_retry: 5
uaa/internal/password_min_length: 0
uaa/internal/password_min_lowercase: 0
uaa/internal/password_min_numeric: 0
uaa/internal/password_min_special: 0
uaa/internal/password_min_uppercase: 0
uaa/proxy_ips_regex: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
uaa_session_cookie_max_age: 28800
uaa_session_idle_timeout: 1800
