additional_api_url_1: https://app.datadoghq.com
additional_api_url_2: https://app.datadoghq.com
additional_api_url_3: https://app.datadoghq.com
additional_api_url_4: https://app.datadoghq.com
additional_api_url_5: https://app.datadoghq.com
address_tag: true
agent_listen_port: "17123"
api_url: https://app.datadoghq.com
app_metrics: true
check_runners: "1"
disable_access_control: false
enable_gohai: true
firehose_subscription_id: datadog-firehose-subscription-id
flush_duration_seconds: 15
flush_max_bytes: 2097152
forwarder_num_workers: "1"
generate_disk_config: true
generate_disk_config_all_partitions: true
generate_disk_config_tag_by_filesystem: true
generate_monit_processes: true
generate_ntp_config: true
generate_ntp_config_host: 0.ubuntu.pool.ntp.org
generate_processes: true
generate_system_processes: true
grab_interval: 10
insecure_ssl_skip_verify: false
ip_tag: true
num_workers: 4
process_agent_enabled: true
trace_agent: true
use_friendly_hostname: true
use_uuid_hostname: false
