---
jobs:
- name: job-hello-world
  public: true
  plan:
  - task: get-pivnet-token
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: sh
        args: [-c, 'echo Credhub value: $credhub_token']
    params: 
      credhub_token: ((pivnet_token))